### ISSUE TITLE
[功能建议]定期备份服务器文件

### ISSUE THREAD

**Issue by ziyic** [Suwings/MCSManager#341]
**你对哪些功能有建议或想法？**
是否可能新增一个功能使面板可以定期备份服务器文件

**这些功能有哪些代替方案？**
暂时没想到（或许是面板程序外的在用作服务端的计算机手动备份）

**对应你提出的内容，你觉得有什么价值？**
避免非服主/管理员的玩家对服务器进行恶意破坏，造成不可逆的损失

**其他内容:**

（功能请求或者功能建议均准许自由发挥，无特定限制模板，你可以在这里写下任何你想说的文字。）

**Comment by Suwings** [comment]
感谢提供建议，目前暂无相关的计划。目前的备份功能可以由Minecraft的插件来辅助进行备份，相信论坛中有不少的备份插件。

**Comment by ACGMC** [comment]
我在用的备份脚本Linux
备份mc地图还不错我用了1年了,想备份哪个目录要自定义,地图不需要整个备份的
https://github.com/ACGMC/Linux_Backup_Minecraft

**Comment by huangsijun17** [comment]
强烈反对在面板中加入服务端自动备份的功能。
一则是可能会和服务端内置的备份功能冲突备份备份文件。
二则是面板很难了解服务端是否可以被热备份，从而导致服务端在运行时可能备份操作，轻则备份无效，重则直接毁坏地图。

**Comment by Kiritow** [comment]
用定时任务+脚本不就可以搞这个事情么...
启动脚本基于tmux启动一个终端，然后挂着就行了
定时任务attach到终端然后输入命令关闭自动保存、强制刷新写盘、操作tar生成备份、重新启动自动保存

**Comment by AlexanderMC8533** [comment]
> 强烈反对在面板中加入服务端自动备份的功能。
> 一则是可能会和服务端内置的备份功能冲突备份备份文件。
> 二则是面板很难了解服务端是否可以被热备份，从而导致服务端在运行时可能备份操作，轻则备份无效，重则直接毁坏地图。

修改方案：备份前关闭服务器（先执行save-all指令，然后执行reload，最后关闭stop），检测服务器是否已关闭，如果关闭，立即执行备份到用户指定目录（单向同步：服务端源》》备份源），监控进度，完成后校验是否文件完全一致，不一致的话目标文件再次单向同步，传输完毕后服务器自启

**Comment by AlexanderMC8533** [comment]
> 强烈反对在面板中加入服务端自动备份的功能。
> 一则是可能会和服务端内置的备份功能冲突备份备份文件。
> 二则是面板很难了解服务端是否可以被热备份，从而导致服务端在运行时可能备份操作，轻则备份无效，重则直接毁坏地图。

任何服务端都支持热备份，只要服务器关闭（mohist除外，因为mohist内置专属JAVAruntime

**Comment by AlexanderMC8533** [comment]
> 用定时任务+脚本不就可以搞这个事情么...
> 启动脚本基于tmux启动一个终端，然后挂着就行了
> 定时任务attach到终端然后输入命令关闭自动保存、强制刷新写盘、操作tar生成备份、重新启动自动保存

轻则无法启动，重则数据损坏
不建议干涉服务端运行，

**Comment by AlexanderMC8533** [comment]
> 我在用的备份脚本Linux
> 备份mc地图还不错我用了1年了,想备份哪个目录要自定义,地图不需要整个备份的
> https://github.com/ACGMC/Linux_Backup_Minecraft

很遗憾，这个方式只适用于Linux，对于Windows仍然无法实现

**Comment by Kiritow** [comment]
插件了解一下？[ServerRestorer](https://www.spigotmc.org/resources/serverrestorer.48853)

**Comment by AlexanderMC8533** [comment]
这个插件会对硬盘固定区域重复擦写，不是长久之计



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] [功能建议]定期备份服务器文件 (#341)




 
插件了解一下？ServerRestorer
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ACGMC** [comment]
> > 我在用的备份脚本Linux
> > 备份mc地图还不错我用了1年了,想备份哪个目录要自定义,地图不需要整个备份的
> > https://github.com/ACGMC/Linux_Backup_Minecraft
> 
> 很遗憾，这个方式只适用于Linux，对于Windows仍然无法实现

windows自带有个历史与备份 好用的

**Comment by AlexanderMC8533** [comment]
谢谢，已实现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午12:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] [功能建议]定期备份服务器文件 (#341)




   
我在用的备份脚本Linux
 备份mc地图还不错我用了1年了,想备份哪个目录要自定义,地图不需要整个备份的
 https://github.com/ACGMC/Linux_Backup_Minecraft
  
很遗憾，这个方式只适用于Linux，对于Windows仍然无法实现
  
windows自带有个历史与备份 好用的
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderMC8533** [comment]
save-all指令也可以避免崩溃导致的数据丢失



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午12:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] [功能建议]定期备份服务器文件 (#341)




   
我在用的备份脚本Linux
 备份mc地图还不错我用了1年了,想备份哪个目录要自定义,地图不需要整个备份的
 https://github.com/ACGMC/Linux_Backup_Minecraft
  
很遗憾，这个方式只适用于Linux，对于Windows仍然无法实现
  
windows自带有个历史与备份 好用的
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderMC8533** [comment]
其实使用插件也会占用服务端的内存，并不想这样搞，所以我觉得save-all指令和热备份是最好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] [功能建议]定期备份服务器文件 (#341)




 
插件了解一下？ServerRestorer
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kiritow** [comment]
有一说一，最简单而且最保险的方法是定期重启服务器

**Comment by AlexanderMC8533** [comment]
确实，我每3小时重启一次



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月5日(周四) 中午12:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] [功能建议]定期备份服务器文件 (#341)




 
有一说一，最简单而且最保险的方法是定期重启服务器
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huangsijun17** [comment]
> > 强烈反对在面板中加入服务端自动备份的功能。
> > 一则是可能会和服务端内置的备份功能冲突备份备份文件。
> > 二则是面板很难了解服务端是否可以被热备份，从而导致服务端在运行时可能备份操作，轻则备份无效，重则直接毁坏地图。
> 
> 任何服务端都支持热备份，只要服务器关闭（mohist除外，因为mohist内置专属JAVAruntime

1.7.10的原版不支持，部分模组、插件不支持，部分服务端甚至使用了SQL数据库，如背包跨服，都会出现问题。
