### ISSUE TITLE
关于文件管理器默认目录

### ISSUE THREAD

**Issue by liaojinmin** [Suwings/MCSManager#458]
如题，如何设置【普通用户】打开文件管理器只可访问【mod】【plugins】其它禁止访问也禁止操作，

**Comment by Suwings** [comment]
暂时不支持如此细化的权限控制。

**Comment by huangsijun17** [comment]
我非常好奇您只允许用户访问mod和plugins的目的。如是设置，mcsm的普通用户无法/难以查看/修改其模组设置、动态库文件、spigot设置、bukkit设置、白名单、uuid等等等等。
而常见的mc插件中不乏各种高权限的插件。既然允许mc的服务端与插件访问/修改文件，缺不允许使用面板的文件管理来进行管理，我属实看不懂。

**Comment by Kiritow** [comment]
可以在自定义服务器模式下，调整服务器根目录到一个仅包含`mods`和`plugins`的文件夹. 在其外层再通过符号链接等方式, 将两个文件夹软链过去. 服务器启动方式改为外层的启动脚本即可.

**Comment by Kiritow** [comment]
可以在自定义服务器模式下，调整服务器根目录到一个仅包含`mods`和`plugins`的文件夹. 在其外层再通过符号链接等方式, 将两个文件夹软链过去. 服务器启动方式改为外层的启动脚本即可.

**Comment by AlexanderMC8533** [comment]
弊端：
1.从级操作者无法修改配置文件，对用户造成不便
2.用户无法通过logs文件夹访问日志资料（logs类资料）排查故障
3.文件无法清理
4.不能对服务器细节内容进行修改（bukkit.yml）
（使用简洁语言避免 非人话）

**Comment by huangsijun17** [comment]
> 可以在自定义服务器模式下，调整服务器根目录到一个仅包含`mods`和`plugins`的文件夹. 在其外层再通过符号链接等方式, 将两个文件夹软链过去. 服务器启动方式改为外层的启动脚本即可.

在MCSM的管理员模式下依然无法修改其他文件。

**Comment by AlexanderMC8533** [comment]
个人认为，这样只能进行基本开服操作，而需要的东西往往没有
比如某些服主会为了服务器更好玩来买端，但是如果在这样的设定下无法达到预期



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月11日(周三) 上午8:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Suwings/MCSManager] 关于文件管理器默认目录 (#458)




 
我非常好奇您只允许用户访问mod和plugins的目的。如是设置，mcsm的普通用户无法/难以查看/修改其模组设置、动态库文件、spigot设置、bukkit设置、白名单、uuid等等等等。
 而常见的mc插件中不乏各种高权限的插件。既然允许mc的服务端与插件访问/修改文件，缺不允许使用面板的文件管理来进行管理，我属实看不懂。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liaojinmin** [comment]
我主要想禁止修改服务端核心.jar

**Comment by liaojinmin** [comment]
还有服务器端口这方面，

**Comment by liaojinmin** [comment]
借助这我问个问题，就是面板使用的nginx进行反向代理，并使用了CDN 虽然证实了是CDN的原因，导致在特定秒比如60S就必须刷新页面才能正常操作，一般无操作到达30S就会一直提示断开连接，请问有什么好办法呢，CDN这边腾讯云，找不到合适的设置

**Comment by AlexanderMC8533** [comment]
套什么CDN，只有加大带宽才能。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月11日(周三) 下午5:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 关于文件管理器默认目录 (#458)




 
借助这我问个问题，就是面板使用的nginx进行反向代理，并使用了CDN 虽然证实了是CDN的原因，导致在特定秒比如60S就必须刷新页面才能正常操作，一般无操作到达30S就会一直提示断开连接，请问有什么好办法呢，CDN这边腾讯云，找不到合适的设置
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderMC8533** [comment]
无法解决你的问题。因为无法定位问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月11日(周三) 上午9:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 关于文件管理器默认目录 (#458)




  
可以在自定义服务器模式下，调整服务器根目录到一个仅包含mods和plugins的文件夹. 在其外层再通过符号链接等方式, 将两个文件夹软链过去. 服务器启动方式改为外层的启动脚本即可.
  
在MCSM的管理员模式下依然无法修改其他文件。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderMC8533** [comment]
这一条你可以雇佣程序员，等待发行后按需修改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月11日(周三) 下午5:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 关于文件管理器默认目录 (#458)




 
我主要想禁止修改服务端核心.jar
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AlexanderMC8533** [comment]
请问，这个issue可以close了吗
