### ISSUE TITLE
无法正常使用面板

### ISSUE THREAD

**Issue by xiayuxingchen** [Suwings/MCSManager#480]
**系统环境:**
windows server 2019
**面板版本:**
8.6
**Node 版本:**

**出现概率:**
%80
**出现的问题 (BUG):**
控制面板卡死，无法进行操作，只能ctrl+c才能暂时解决
**复现操作步骤:**
进行任何操作时

**Comment by AlexanderMC8533** [comment]
无法帮到你
请问mcsm版本能否再详细
如果是最新版请录屏GIF展示故障




Taleling
***@***.***

FutureLand&nbsp;Create&amp;Design&nbsp;Corp.
首席执行官



------------------ 原始邮件 ------------------
发件人: xiayuxingchen ***@***.***&gt;
发送时间: 2021年9月12日 13:20
收件人: Suwings/MCSManager ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Suwings/MCSManager] 无法正常使用面板 (#480)





 
系统环境:
 windows server 2019
 面板版本:
 8.6
 Node 版本:
 
出现概率:
 %80
 出现的问题 (BUG):
 控制面板卡死，无法进行操作，只能ctrl+c才能暂时解决
 复现操作步骤:
 进行任何操作时
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Suwings** [comment]
详细的说一下你是怎么触发这个情况的，步骤，Nodejs 版本（Node -v）。很多人都在使用 MCSM 面板，如果无法正常使用就不会等到现在才有反馈。
