### ISSUE TITLE
命令控制台乱码

### ISSUE THREAD

**Issue by stevensane** [Suwings/MCSManager#482]
命令控制台乱码，但是在控制终端（服务端管理直接点终端按钮的那个小视窗）就没有问题
Ubuntu 20.04.2 LTS
使用的mcdr（python的东西）

**Comment by huangsijun17** [comment]
老毛病老问题了，模拟终端机理的问题，不好解决。
另外，MCDR加上这个参数看一下：`-X utf8`
详见：https://github.com/Suwings/MCSManager/issues/286#issuecomment-665720894

**Comment by Suwings** [comment]
新版本不会有旧版的网页控制台了，这个问题会解决

**Comment by AlexanderMC8533** [comment]
> 新版本不会有旧版的网页控制台了，这个问题会解决

没有控制台怎么使用呢？

**Comment by huangsijun17** [comment]
> > 新版本不会有旧版的网页控制台了，这个问题会解决
> 
> 没有控制台怎么使用呢？

没有的是**旧版的**网页控制台。那玩意原理上就有类似的问题。

**Comment by AlexanderMC8533** [comment]
> > > 新版本不会有旧版的网页控制台了，这个问题会解决
> > 
> > 
> > 没有控制台怎么使用呢？
> 
> 没有的是**旧版的**网页控制台。那玩意原理上会产生类似的问题。

你的意思是说，在新的MCSM中会改进模拟控制台 这功能

**Comment by huangsijun17** [comment]
> > > > 新版本不会有旧版的网页控制台了，这个问题会解决
> > > 
> > > 
> > > 没有控制台怎么使用呢？
> > 
> > 
> > 没有的是**旧版的**网页控制台。那玩意原理上会产生类似的问题。
> 
> 你的意思是说，在新的MCSM中会改进模拟控制台 这功能

你搞错新旧的次序了，模拟控制台反而是**更新**的那一个。不过，模拟控制台应该也会被干掉。

**Comment by AlexanderMC8533** [comment]
就是那个输出的地方会做改进以及修复问题吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月18日(周六) 中午11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suwings/MCSManager] 命令控制台乱码 (#482)




     
新版本不会有旧版的网页控制台了，这个问题会解决
  
没有控制台怎么使用呢？
  
没有的是旧版的网页控制台。那玩意原理上会产生类似的问题。
  
你的意思是说，在新的MCSM中会改进模拟控制台 这功能
  
你搞错新旧的次序了，模拟控制台反而是更新的那一个。不过，模拟控制台应该也会被干掉。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ldxw** [comment]
![image](https://user-images.githubusercontent.com/25827746/136234354-c242032b-08d4-42d2-9871-5e5cca10c0bf.png)
我是这个问题。。。

**Comment by huangsijun17** [comment]
> ![image](https://user-images.githubusercontent.com/25827746/136234354-c242032b-08d4-42d2-9871-5e5cca10c0bf.png) 我是这个问题。。。

经典的编码错误，修改utf-8或者gbk试一下。
