### ISSUE TITLE
希望添加 Java 版本管理

### ISSUE THREAD

**Issue by Taskeren** [Suwings/MCSManager#488]
**你对哪些功能有建议或想法？**
因为 1.17 之后需要 Java16，然后老的版本仍然需要 Java8，在设置实例的 Java 版本时要输入全地址很麻烦，所以我希望能够推出一个 Java 版本管理，然后可以在设置实例的时候可以直接选择。

**这些功能有哪些代替方案？**
/

**对应你提出的内容，你觉得有什么价值？**
方便服主对 Java 版本的管理

**其他内容:**
/

**Comment by Suwings** [comment]
了解，谢谢你的意见，随后会慢慢推出的。

**Comment by huangsijun17** [comment]
我之前也感觉这个功能挺好的，直到用了Docker。
直接管理Docker的版本不香吗？

**Comment by AlexanderMC8533** [comment]
我觉得Windows使用docker，技术门槛太高了




Taleling
***@***.***

FutureLand&nbsp;Create&amp;Design&nbsp;Corp.
首席执行官


&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Suwings/MCSManager"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月3日(星期天) 晚上8:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Suwings/MCSManager] 希望添加 Java 版本管理 (#488)





 
我之前也感觉这个功能挺好的，直到用了Docker。
 直接管理Docker的版本不香吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
