### ISSUE TITLE
能否在版本9发布以后继续对8进行安全更新和bug修复？

### ISSUE THREAD

**Issue by CreeperKong** [Suwings/MCSManager#489]
能否在版本9发布以后继续对8进行安全更新和bug修复？

**Comment by Suwings** [comment]
会再最后维护一段时间，但不会一直维护。

**Comment by AlexanderMC8533** [comment]
这个我可以提作者回答
后面8版本没有致命bug的话，不会再对8版本维护


还有，你要知道，维护俩套代码很麻烦
本来就是开源的












Taleling
***@***.***

FutureLand&nbsp;Create&amp;Design&nbsp;Corp.
首席执行官

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月15日(周五) 晚上11:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Suwings/MCSManager] 能否在版本9发布以后继续对8进行安全更新和bug修复？ (#489)




 
能否在版本9发布以后继续对8进行安全更新和bug修复？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
